apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-services-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managed-services
  template:
     metadata:
      labels:
        app: managed-services
     spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: managed-services-container
        image: 537972007847.dkr.ecr.us-east-2.amazonaws.com/cp-managed-services:latest
        imagePullPolicy: Always
        env:
        - name: AUTH-SERVICE-ENDPOINT
          value: "http://auth-service-svc:6000"
        - name: JDBC_CONNECTION_STRING
          value: "jdbc:sqlserver://172.31.36.126:1433;databaseName=pms"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "Excel@1234"
        - name: MANAGED_SERVICES_SERVER_URL
          value: "https://api.synerzip.in/managed-services"
        - name: JWT_PUBLIC_KEY
          value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7+lMmYV8o1ClJx7Ja7cy\nBxk6AIwhBfdPMmpKcNox4yeRvVK//293+fQU+db5kjXoYOgfOI3RVEgy/CHA5JYa\n+yAAHD+JuhABLKA/XuEnfKeePwXqP62tDjkWMH/TRB/6hPm2wXq9jKcfNuxgKTTj\nZsLD/FegB3RJwA1yUcTnW4B9zNam3nIfKESD1C+4H4x15L/9IGU08fcH1+XlK/S1\n3gS3cbK9HTvAPt0GyUhqrX/Jxran+Nyc5g74R+u9Vy4Gb9VQIJtWxxL+lAD5nieG\n7ehfuL+YYYM4OOfNrvT075/YYoCVsmEgc2A/yrIo9eZ0r/SWFCAGyWHOdDin8xJj\nYQIDAQAB\n-----END PUBLIC KEY-----" 
        ports:
        - containerPort: 5005
